services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Jakarta
      APP_PORT: ${APP_PORT:-3000}
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}
      MAILJET_SENDER: ${MAILJET_SENDER}
      JWT_SECRET: ${JWT_SECRET}
      GIN_MODE: ${GIN_MODE:-debug}
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Jakarta
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    command: --default-time-zone='+07:00'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD}
      volumes:
        - redis_data:/data
      restart: unless-stopped

volumes:
  mysql_data:
  redis_data: